services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: infra-replicant-docs:local
    container_name: infra-replicant-docs
    restart: unless-stopped
    ports:
      - "192.168.18.220:8082:80"
